services:
  ollama:
    image: ollama/ollama
    container_name: ${OLLAMA_HOST}
    ports:
      - "${OLLAMA_PORT}:${OLLAMA_PORT}"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - global
    restart: unless-stopped

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    networks:
      - global

networks:
  global:
    driver: bridge

volumes:
  ollama_data:
