services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "${ollama_port}:${ollama_port}"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app

volumes:
  ollama_data:
