services:
  ollama:
    image: ollama/ollama
    container_name: ${OLLAMA_HOST}
    ports:
      - "${OLLAMA_PORT}:${OLLAMA_PORT}"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app

volumes:
  ollama_data:
